# Generated by Django 6.0.2 on 2026-02-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='output_file',
            field=models.FileField(blank=True, null=True, upload_to='job_outputs/'),
        ),
    ]
