# Generated by Django 6.0.2 on 2026-02-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_output_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='environment_file',
            field=models.FileField(blank=True, help_text='Optional: environment.yaml for extra dependencies', null=True, upload_to='environments/'),
        ),
    ]
