# Generated by Django 5.2.11 on 2026-02-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_environment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='environment_file',
            field=models.FileField(blank=True, help_text='The environment.yaml or renv.lock file', null=True, upload_to='environments/'),
        ),
    ]
