version: '3.8'

services:
  # PostgreSQL
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: notebook_db
      POSTGRES_USER: notebook_user
      POSTGRES_PASSWORD: notebook_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  # Minio (S3 mock )
  minio:
    image: minio/minio
    ports:
      - "9000:9000" #API
      - "9001:9001" #UI
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  # Create S3 bucket on startup
  minio-setup:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      echo 'Waiting for MinIO...' &&
      sleep 5;
      /usr/bin/mc alias set myminio http://minio:9000 admin password123;
      /usr/bin/mc mb myminio/notebooks-bucket || true;
      /usr/bin/mc anonymous set public myminio/notebooks-bucket;
      echo 'Bucket setup complete.';
      exit 0;
      "

  # Django
  web:
    build:
      context: .
      cache_from:
        - type=gha
      cache_to:
        - type=gha,mode=max
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=local
      - DATABASE_URL=postgres://notebook_user:notebook_password@db:5432/notebook_db
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password123
      - AWS_STORAGE_BUCKET_NAME=notebooks-bucket
      - AWS_S3_ENDPOINT_URL=http://minio:9000
      - WORKER_CALLBACK_URL=http://host.minikube.internal:8000 
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db
      - redis
      - minio-setup

  # Celery
  celery:
    build:
      context: .
      cache_from:
        - type=gha
      cache_to:
        - type=gha,mode=max
    command: celery -A notebook_platform worker -l info
    volumes:
      - .:/app
    environment:
      - ENVIRONMENT=local
      - DATABASE_URL=postgres://notebook_user:notebook_password@db:5432/notebook_db
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password123
      - AWS_STORAGE_BUCKET_NAME=notebooks-bucket
      - AWS_S3_ENDPOINT_URL=http://minio:9000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db
      - redis
      - minio-setup

volumes:
  postgres_data:
  minio_data: