name: End-to-End Pipeline

on:
  push:
  pull_request:

permissions:
  contents: read
  actions: write

jobs:
  test-platform:
    runs-on: ubuntu-latest
    
    env:
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_EMAIL: admin@example.com
      DJANGO_SUPERUSER_PASSWORD: password123

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - name: Start Minikube
        uses: medyagh/setup-minikube@latest
        with:
          start: true
          cache: true
          minikube-version: latest
          wait: all
          addons: registry
          insecure-registry: "10.0.0.0/24,192.168.0.0/16,172.16.0.0/12,localhost:5000"

      - name: Expose Registry to Host
        run: docker run --rm -d --network=host alpine ash -c "apk add socat && socat TCP-LISTEN:5000,reuseaddr,fork TCP:$(minikube ip):5000"

      - name: Setup Kubernetes Permissions
        run: kubectl apply -f ./server/minikube-rbac.yaml

      - name: Build & Push Worker Image
        uses: docker/build-push-action@v5
        with:
          context: ./worker
          tags: localhost:5000/r-notebook-worker:latest
          push: true 
          cache-from: type=gha,scope=worker-cache
          cache-to: type=gha,mode=max,scope=worker-cache

      - name: Build & Push Web Image
        uses: docker/build-push-action@v5
        with:
          context: ./server
          tags: localhost:5000/notebook-web:latest
          push: true 
          cache-from: type=gha,scope=web-cache
          cache-to: type=gha,mode=max,scope=web-cache

      - name: Build & Push Celery Image
        uses: docker/build-push-action@v5
        with:
          context: ./server
          tags: localhost:5000/notebook-celery:latest
          push: true
          cache-from: type=gha,scope=celery-cache
          cache-to: type=gha,mode=max,scope=celery-cache

      - name: Start the Application Stack
        working-directory: ./server
        run: docker compose up -d

      - name: Start the Kubectl Proxy Bridge in the Background
        run: |
          kubectl proxy --address='0.0.0.0' --port=8001 --accept-hosts='^.*' &
          echo "Kubernetes bridge is open!"

      - name: Run Database Migrations & Setup
        working-directory: ./server
        run: |
          sleep 5 
          docker compose exec -T web python manage.py migrate
          docker compose exec -T web python manage.py createsuperuser --noinput || true

      - name: Check Web Server Health (Login Screen)
        run: |
          echo "Testing connection to http://localhost:8000/login/ ..."

          STATUS=$(curl -sL -o /dev/null -w "%{http_code}" http://localhost:8000/login/)
          
          if [ "$STATUS" -eq 200 ]; then
            echo "Login screen is up."
            exit 0
          else
            echo "Web server failed with $STATUS."
            docker compose logs web
            exit 1
          fi